# basic options
title: Didlie Blog
author: Isaac Jacobs
email: everforward@live.com
description: Didlie blog for news, questions, comments and criticism.
github_username: didlie

# Build settings
markdown: kramdown
theme: minima
